### ISSUE TITLE
SimView - rephrase buttons

### ISSUE THREAD

**Issue by MyKaez** [MyKaez/btc-playground#18]
- when in simulations, the start Button in confusing 

@DannyOrangeRelationship how to rephrase?
"Home"?

![Screenshot_20220802-220530_Chrome.jpg](https://user-images.githubusercontent.com/28479564/182463973-092c37a1-bda8-4075-8fb7-5512273f95d3.jpg)

**Comment by DannyOrangeRelationship** [comment]
I will close this issue. Please take a look at our UI revision concept: https://github.com/MyKaez/btc-playground/issues/24#issue-1335612054
