### ISSUE TITLE
UI revision

### ISSUE THREAD

**Issue by DannyOrangeRelationship** [MyKaez/btc-playground#24]
@MyKaez please separate the following points in more than one issues:

**General**
- add bread crumbs for a better overview / navigation through the whole pages
- highlight simulation button
- /home "Bitcoin Simulation" should be a bigger headerline
- delete Twitter-/Git-Icon from header and bring it to /info  
- /pow add "Options" to "Input"
- /pow delete selection for "Aktion"
- /pow make it clear "Berechnungen" are outputs
- /pow bring "Definition" and "Rechnung" together
- /pow change blue to write block selection for input/output
- /pow "HashRate" change to "Zyklen"
- /pow change "Input" formula to a clean .png formula (Danny will add it to /assets)
- /pow separate the text above CMD with returns
- /pow set default value for "Angezeige Hashes" to 16

**Mobile**
- attach header while scrolling 

**Desktop**
- make selections more clear for better overview / navigation
- /home more space for main page

**Comment by MyKaez** [comment]
I implemented different topics, for the other ones I created new tickets:
- #25 
- #26 
- #27 
- #28 
- #29
