### ISSUE TITLE
Web - Forwarding does Not Work properly

### ISSUE THREAD

**Issue by MyKaez** [MyKaez/btc-playground#8]
This can nee called:
fixesth.is/btc-playground

This cannot bei called:
fixesth.is/btc-playground/home

The Server needs top Forward the falls correctly

**Comment by DannyOrangeRelationship** [comment]
We got this message:

_vielen Dank für Ihre E-Mail.

Wenn man über den Link ../simulations oder ../home versucht die Webseite aufzurufen, wird hier Plesk erstmal nichts finden, weil es die Verzeichnisse so erstmal nicht gibt. 

Ruft man aber die [https://fixesth.is/btc-playground](https://deref-gmx.net/mail/client/FKY-liGHxCc/dereferrer/?redirectUrl=https%3A%2F%2Ffixesth.is%2Fbtc-playground)  Adresse auf, befindet sich dort der Inhalt, welcher zur Navigation benötigt wird und es wird an /home weitergeleitet. Das kann aber erst ausgeführt werden, wenn das Basisverzeichnis aufgerufen wurde.

Theoretisch kann man das ganze mit folgenden Einträgen in der .htaccess "fixen". Das führt dazu das nicht gefundene Verzeichnisse oder Links erstmal wieder an die index.html gesendet werden.

RewriteEngine On
Options +SymLinksIfOwnerMatch
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]

Mit freundlichen Grüßen_

**Comment by DannyOrangeRelationship** [comment]
On the other side we can host the page in the root dir - maybe this should be fix this issue

**Comment by MyKaez** [comment]
solved with this doc, thanks to @Pandabyts 
https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html
